# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtercatalog',
            options={'verbose_name': '\u0424\u0438\u043b\u044c\u0442\u0440', 'verbose_name_plural': '\u0444\u0438\u043b\u044c\u0442\u0440\u044b'},
        ),
        migrations.AlterField(
            model_name='filtercatalog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='filtercatalog',
            name='published',
            field=models.BooleanField(default=True, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='filtercatalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='filterselect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='filterselect',
            name='published',
            field=models.BooleanField(default=True, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='filterselect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='itemfilter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='itemfilter',
            name='published',
            field=models.BooleanField(default=True, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='itemfilter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f'),
        ),
    ]
