# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('url', models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u043f\u0443\u0441\u0442\u044b\u043c \u0434\u043b\u044f \u0430\u0432\u0442\u043e\u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f', max_length=255, null=True, verbose_name='URL \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430')),
                ('top_menu', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0432 \u0442\u043e\u043f-\u043c\u0435\u043d\u044e')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ['tree_id'],
                'db_table': 'Catalog',
                'verbose_name': '\u043a\u0430\u0442\u0430\u043b\u043e\u0433',
                'verbose_name_plural': '\u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0438',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('add_filter', models.BooleanField(default=True, verbose_name='\u0420\u0430\u0437\u0440\u0435\u0448\u0438\u0442\u044c \u0444\u0438\u043b\u044c\u0442\u0440\u043e\u0432\u0430\u0442\u044c?')),
                ('f_type', models.CharField(blank=True, choices=[('textfield', '\u0422\u0435\u043a\u0441\u0442\u043e\u0432\u044b\u0439'), ('int', '\u0426\u0435\u043b\u043e\u0435'), ('float', 'Float'), ('boolean', '\u041b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u0438\u0439')], default=[('textfield', '\u0422\u0435\u043a\u0441\u0442\u043e\u0432\u044b\u0439')], max_length=100, null=True, verbose_name='\u0422\u0438\u043f')),
                ('f_widget', models.CharField(blank=True, choices=[('text', '\u0422\u0435\u043a\u0441\u0442\u043e\u0432\u044b\u0439'), ('checkbox', 'checkbox'), ('textarea', 'textarea'), ('radio', 'radio')], default=[('textfield', '\u0422\u0435\u043a\u0441\u0442\u043e\u0432\u044b\u0439')], max_length=100, null=True, verbose_name='\u0412\u0438\u0434\u0436\u0435\u0442')),
                ('values', models.TextField(blank=True, null=True, verbose_name='\u0414\u043e\u043f\u0443\u0441\u0442\u0438\u043c\u044b\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f')),
            ],
            options={
                'db_table': 'Feature',
                'verbose_name': '\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430',
                'verbose_name_plural': '\u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430')),
                ('block_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0431\u043b\u043e\u043a\u0430')),
                ('block_size', models.CharField(choices=[('sm', '\u041c\u0430\u043b\u0435\u043d\u044c\u043a\u0438\u0439 \u0431\u043b\u043e\u043a 365x268'), ('smh', '\u041c\u0430\u043b\u0435\u043d\u044c\u043a\u0438\u0439 \u0431\u043b\u043e\u043a 365x291'), ('mid', '\u0421\u0440\u0435\u0434\u043d\u0438\u0439 \u0431\u043b\u043e\u043a 555x386'), ('lg', '\u0411\u043e\u043b\u044c\u0448\u043e\u0439 \u0431\u043b\u043e\u043a 745x291')], default='sm', max_length=3, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0431\u043b\u043e\u043a\u0430')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('link_type', models.CharField(choices=[('arr', '\u0421\u0442\u0440\u0435\u043b\u043a\u043e\u0439'), ('lnk', '\u041a\u043d\u043e\u043f\u043a\u043e\u0439')], default='lnk', max_length=3, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0443 \u0441\u0442\u0440\u0435\u043b\u043a\u043e\u0439 \u0438\u043b\u0438 \u043a\u043d\u043e\u043f\u043a\u043e\u0439?')),
                ('button_text', models.CharField(default='\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0439', max_length=20, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435')),
                ('catalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Shop.Catalog', verbose_name='\u041a\u0430\u0442\u0430\u043b\u043e\u0433')),
            ],
            options={
                'db_table': 'HomeBlock',
                'verbose_name': '\u0411\u043b\u043e\u043a \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435',
                'verbose_name_plural': '\u0431\u043b\u043e\u043a\u0438 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=255, verbose_name='Title')),
                ('seo_desc', models.CharField(max_length=500, verbose_name='Description')),
            ],
            options={
                'db_table': 'HomePage',
                'verbose_name': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
            },
        ),
        migrations.CreateModel(
            name='HomeSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.HomePage', verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
            ],
            options={
                'db_table': 'HomeSpecial',
                'verbose_name': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0441\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('url', models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u043f\u0443\u0441\u0442\u044b\u043c \u0434\u043b\u044f \u0430\u0432\u0442\u043e\u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f', max_length=255, null=True, unique=True, verbose_name='URL \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430')),
                ('price', models.IntegerField(default=0, verbose_name='\u0426\u0435\u043d\u0430')),
                ('quantity', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('is_discont', models.BooleanField(default=False, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430?')),
                ('old_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u0421\u0442\u0430\u0440\u0430\u044f \u0446\u0435\u043d\u0430')),
                ('short_desc', models.TextField(blank=True, max_length=300, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('detail_desc', models.TextField(blank=True, default='\u0412 \u0441\u0442\u0430\u0434\u0438\u0438 \u043d\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f...', verbose_name='\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('created', models.DateField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated', models.DateField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('catalog', models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='Shop.Catalog', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0438\u0439 \u043a\u0430\u0442\u0430\u043b\u043e\u0433')),
            ],
            options={
                'db_table': 'Item',
                'verbose_name': '\u0442\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0442\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='ItemsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.Item', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'db_table': 'ItemsImage',
                'verbose_name': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0438\u0437\u0430\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.AddField(
            model_name='homespecial',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Shop.Item', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='homeblock',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.HomePage', verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='Shop.Feature', verbose_name='\u0414\u043e\u043f\u0443\u0441\u0442\u0438\u043c\u044b\u0435 \u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Shop.Catalog'),
        ),
    ]
