# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 23:20
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
