# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_catalog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Catalog', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0438\u0439 \u043a\u0430\u0442\u0430\u043b\u043e\u0433'),
        ),
    ]
