# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20170929_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Shop.Feature')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Shop.Feature')),
            ],
            options={
                'get_latest_by': 'pk',
                'ordering': ['feature'],
                'verbose_name_plural': '\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u043f\u043e\u043b\u0435\u0439',
                'db_table': 'FeatureValues',
                'verbose_name': '\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u043f\u043e\u043b\u044f',
            },
        ),
        migrations.AlterField(
            model_name='catalog',
            name='features',
            field=models.ManyToManyField(blank=True, to='Shop.Feature', verbose_name='\u0414\u043e\u043f\u0443\u0441\u0442\u0438\u043c\u044b\u0435 \u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='item',
            name='catalog',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='Shop.Catalog', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0438\u0439 \u043a\u0430\u0442\u0430\u043b\u043e\u0433'),
        ),
    ]
