# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.Brand', verbose_name='\u0411\u0440\u0435\u043d\u0434'),
        ),
    ]
