# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 06:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_auto_20171217_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='seo_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u0421\u0415\u041e \u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u0421\u0415\u041e \u0442\u0435\u043a\u0441\u0442'),
        ),
    ]
